[custom]
;解决DNS泄露，无分流群组
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
##ruleset=美国节点,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
##ruleset=美国节点,https://raw.githubusercontent.com/ybb357889/ybb357889/refs/heads/main/google.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ybb357889/ybb357889/refs/heads/main/google.list
ruleset=泰国节点,https://raw.githubusercontent.com/ybb357889/ybb357889/refs/heads/main/tl_phone30_39.list
ruleset=马来节点,https://raw.githubusercontent.com/ybb357889/ybb357889/refs/heads/main/ml_phone40_49.list
ruleset=新加坡节点,https://raw.githubusercontent.com/ybb357889/ybb357889/refs/heads/main/sg_phone50_59.list
ruleset=美国节点,https://raw.githubusercontent.com/ybb357889/ybb357889/refs/heads/main/usa_phone60_69.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=马来节点`url-test`(马来西亚|Malaysia)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=香港节点`url-test`(香港|HongKong|Hong Kong|HK)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=泰国节点`url-test`(泰国|Thailand)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=美国节点`url-test`(美国|USA)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=新加坡节点`url-test`(新加坡|Singapore)`http://www.gstatic.com/generate_204`300,,50

enable_rule_generator=true
overwrite_original_rules=true
